//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERVIS_WEB_PROYECTO.ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLETA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOLETA()
        {
            this.DETALLEBOLETA = new HashSet<DETALLEBOLETA>();
        }
    
        public int NUM_BOL { get; set; }
        public System.DateTime FEC_BOL { get; set; }
        public int idCarrera { get; set; }
        public int codAlu { get; set; }
    
        public virtual TBAlumno TBAlumno { get; set; }
        public virtual TBCarrera TBCarrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLEBOLETA> DETALLEBOLETA { get; set; }
    }
}
