//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERVIS_WEB_PROYECTO.ModeloDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDInstituto2Entities : DbContext
    {
        public BDInstituto2Entities()
            : base("name=BDInstituto2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOLETA> BOLETA { get; set; }
        public virtual DbSet<DETALLEBOLETA> DETALLEBOLETA { get; set; }
        public virtual DbSet<TBAlumno> TBAlumno { get; set; }
        public virtual DbSet<TBAsignatura> TBAsignatura { get; set; }
        public virtual DbSet<TBCarrera> TBCarrera { get; set; }
        public virtual DbSet<TBLibro> TBLibro { get; set; }
        public virtual DbSet<TBMatricula> TBMatricula { get; set; }
        public virtual DbSet<TBProfesor> TBProfesor { get; set; }
        public virtual DbSet<TBSede> TBSede { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual int actualizaProfe(Nullable<int> cod, string nombre, string apellido, string dni, string correo, string celular)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var celularParameter = celular != null ?
                new ObjectParameter("celular", celular) :
                new ObjectParameter("celular", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("actualizaProfe", codParameter, nombreParameter, apellidoParameter, dniParameter, correoParameter, celularParameter);
        }
    
        public virtual ObjectResult<buscaProfe_Result> buscaProfe(Nullable<int> cod)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<buscaProfe_Result>("buscaProfe", codParameter);
        }
    
        public virtual int eliminaProfe(Nullable<int> cod)
        {
            var codParameter = cod.HasValue ?
                new ObjectParameter("cod", cod) :
                new ObjectParameter("cod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("eliminaProfe", codParameter);
        }
    
        public virtual int insertaProfe(string nombre, string apellido, string dni, string correo, string celular)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var celularParameter = celular != null ?
                new ObjectParameter("celular", celular) :
                new ObjectParameter("celular", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertaProfe", nombreParameter, apellidoParameter, dniParameter, correoParameter, celularParameter);
        }
    
        public virtual ObjectResult<listaProfe_Result> listaProfe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<listaProfe_Result>("listaProfe");
        }
    
        public virtual int sp_RegistrarUsuario(string correo, string clave, ObjectParameter registrado, ObjectParameter mensaje)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistrarUsuario", correoParameter, claveParameter, registrado, mensaje);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_ValidarUsuario(string correo, string clave)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ValidarUsuario", correoParameter, claveParameter);
        }
    
        public virtual int usp_ActualizarAlumno(Nullable<int> id, string nom, string ape, string dire, string dni, string corre, string fono, string esta)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var apeParameter = ape != null ?
                new ObjectParameter("ape", ape) :
                new ObjectParameter("ape", typeof(string));
    
            var direParameter = dire != null ?
                new ObjectParameter("dire", dire) :
                new ObjectParameter("dire", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var correParameter = corre != null ?
                new ObjectParameter("corre", corre) :
                new ObjectParameter("corre", typeof(string));
    
            var fonoParameter = fono != null ?
                new ObjectParameter("fono", fono) :
                new ObjectParameter("fono", typeof(string));
    
            var estaParameter = esta != null ?
                new ObjectParameter("esta", esta) :
                new ObjectParameter("esta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarAlumno", idParameter, nomParameter, apeParameter, direParameter, dniParameter, correParameter, fonoParameter, estaParameter);
        }
    
        public virtual int usp_ActualizarAsignatura(Nullable<int> idAsignatura, string nomAsignatura)
        {
            var idAsignaturaParameter = idAsignatura.HasValue ?
                new ObjectParameter("idAsignatura", idAsignatura) :
                new ObjectParameter("idAsignatura", typeof(int));
    
            var nomAsignaturaParameter = nomAsignatura != null ?
                new ObjectParameter("nomAsignatura", nomAsignatura) :
                new ObjectParameter("nomAsignatura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarAsignatura", idAsignaturaParameter, nomAsignaturaParameter);
        }
    
        public virtual int usp_ActualizarMatricula(Nullable<int> codMat, Nullable<int> codAlu, Nullable<int> idCarr, string ciclo, Nullable<int> idSede)
        {
            var codMatParameter = codMat.HasValue ?
                new ObjectParameter("codMat", codMat) :
                new ObjectParameter("codMat", typeof(int));
    
            var codAluParameter = codAlu.HasValue ?
                new ObjectParameter("codAlu", codAlu) :
                new ObjectParameter("codAlu", typeof(int));
    
            var idCarrParameter = idCarr.HasValue ?
                new ObjectParameter("idCarr", idCarr) :
                new ObjectParameter("idCarr", typeof(int));
    
            var cicloParameter = ciclo != null ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(string));
    
            var idSedeParameter = idSede.HasValue ?
                new ObjectParameter("idSede", idSede) :
                new ObjectParameter("idSede", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarMatricula", codMatParameter, codAluParameter, idCarrParameter, cicloParameter, idSedeParameter);
        }
    
        public virtual int usp_ActualizarSede(Nullable<int> idSede, string nomSede)
        {
            var idSedeParameter = idSede.HasValue ?
                new ObjectParameter("idSede", idSede) :
                new ObjectParameter("idSede", typeof(int));
    
            var nomSedeParameter = nomSede != null ?
                new ObjectParameter("nomSede", nomSede) :
                new ObjectParameter("nomSede", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarSede", idSedeParameter, nomSedeParameter);
        }
    
        public virtual ObjectResult<usp_BuscarAlumno_Result> usp_BuscarAlumno(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_BuscarAlumno_Result>("usp_BuscarAlumno", idParameter);
        }
    
        public virtual ObjectResult<usp_BuscarAsignatura_Result> usp_BuscarAsignatura(Nullable<int> idAsignatura)
        {
            var idAsignaturaParameter = idAsignatura.HasValue ?
                new ObjectParameter("idAsignatura", idAsignatura) :
                new ObjectParameter("idAsignatura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_BuscarAsignatura_Result>("usp_BuscarAsignatura", idAsignaturaParameter);
        }
    
        public virtual ObjectResult<usp_BuscarMatricula_Result> usp_BuscarMatricula(Nullable<int> idMat)
        {
            var idMatParameter = idMat.HasValue ?
                new ObjectParameter("idMat", idMat) :
                new ObjectParameter("idMat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_BuscarMatricula_Result>("usp_BuscarMatricula", idMatParameter);
        }
    
        public virtual ObjectResult<usp_BuscarSede_Result> usp_BuscarSede(Nullable<int> idSede)
        {
            var idSedeParameter = idSede.HasValue ?
                new ObjectParameter("idSede", idSede) :
                new ObjectParameter("idSede", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_BuscarSede_Result>("usp_BuscarSede", idSedeParameter);
        }
    
        public virtual int usp_EliminarAsignatura(Nullable<int> idAsignatura)
        {
            var idAsignaturaParameter = idAsignatura.HasValue ?
                new ObjectParameter("idAsignatura", idAsignatura) :
                new ObjectParameter("idAsignatura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarAsignatura", idAsignaturaParameter);
        }
    
        public virtual int usp_EliminarSede(Nullable<int> idSede)
        {
            var idSedeParameter = idSede.HasValue ?
                new ObjectParameter("idSede", idSede) :
                new ObjectParameter("idSede", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarSede", idSedeParameter);
        }
    
        public virtual int usp_InsertarAlumno(string nom, string ape, string dire, string dni, string corre, string fono, string esta)
        {
            var nomParameter = nom != null ?
                new ObjectParameter("nom", nom) :
                new ObjectParameter("nom", typeof(string));
    
            var apeParameter = ape != null ?
                new ObjectParameter("ape", ape) :
                new ObjectParameter("ape", typeof(string));
    
            var direParameter = dire != null ?
                new ObjectParameter("dire", dire) :
                new ObjectParameter("dire", typeof(string));
    
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var correParameter = corre != null ?
                new ObjectParameter("corre", corre) :
                new ObjectParameter("corre", typeof(string));
    
            var fonoParameter = fono != null ?
                new ObjectParameter("fono", fono) :
                new ObjectParameter("fono", typeof(string));
    
            var estaParameter = esta != null ?
                new ObjectParameter("esta", esta) :
                new ObjectParameter("esta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarAlumno", nomParameter, apeParameter, direParameter, dniParameter, correParameter, fonoParameter, estaParameter);
        }
    
        public virtual int usp_InsertarAsignatura(string nomAsignatura)
        {
            var nomAsignaturaParameter = nomAsignatura != null ?
                new ObjectParameter("nomAsignatura", nomAsignatura) :
                new ObjectParameter("nomAsignatura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarAsignatura", nomAsignaturaParameter);
        }
    
        public virtual int usp_InsertarMatricula(Nullable<int> codAlu, Nullable<int> idCarr, string ciclo, Nullable<int> idSede)
        {
            var codAluParameter = codAlu.HasValue ?
                new ObjectParameter("codAlu", codAlu) :
                new ObjectParameter("codAlu", typeof(int));
    
            var idCarrParameter = idCarr.HasValue ?
                new ObjectParameter("idCarr", idCarr) :
                new ObjectParameter("idCarr", typeof(int));
    
            var cicloParameter = ciclo != null ?
                new ObjectParameter("ciclo", ciclo) :
                new ObjectParameter("ciclo", typeof(string));
    
            var idSedeParameter = idSede.HasValue ?
                new ObjectParameter("idSede", idSede) :
                new ObjectParameter("idSede", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarMatricula", codAluParameter, idCarrParameter, cicloParameter, idSedeParameter);
        }
    
        public virtual int usp_InsertarSede(string nomSede)
        {
            var nomSedeParameter = nomSede != null ?
                new ObjectParameter("nomSede", nomSede) :
                new ObjectParameter("nomSede", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarSede", nomSedeParameter);
        }
    
        public virtual ObjectResult<usp_listarAlumno_Result> usp_listarAlumno()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarAlumno_Result>("usp_listarAlumno");
        }
    
        public virtual ObjectResult<usp_listarAsignatura_Result> usp_listarAsignatura()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarAsignatura_Result>("usp_listarAsignatura");
        }
    
        public virtual ObjectResult<usp_listarMatricula_Result> usp_listarMatricula()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarMatricula_Result>("usp_listarMatricula");
        }
    
        public virtual ObjectResult<usp_listarSede_Result> usp_listarSede()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listarSede_Result>("usp_listarSede");
        }
    }
}
