//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERVIS_WEB_PROYECTO.ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMatricula
    {
        public short codMat { get; set; }
        public int codAlu { get; set; }
        public int idCarrera { get; set; }
        public string ciclo { get; set; }
        public int idSede { get; set; }
    
        public virtual TBAlumno TBAlumno { get; set; }
        public virtual TBCarrera TBCarrera { get; set; }
        public virtual TBSede TBSede { get; set; }
    }
}
